CREATE PROCEDURE SelectTotals @DATE DATE
AS
SELECT * FROM
(SELECT SUM(Amount) AS TotalWages FROM Salaries) AS s
CROSS JOIN
(SELECT SUM(Amount) AS TotalAllowance FROM Allowance
WHERE DATEPART(YEAR, [Period]) = DATEPART(YEAR, @DATE)
	AND DATEPART(MONTH, [Period]) = DATEPART(MONTH, @DATE)) AS a
CROSS JOIN
(SELECT SUM(Amount) AS TotalBonuses FROM Bonuses
WHERE DATEPART(YEAR, [Period]) = DATEPART(YEAR, @DATE)
	AND DATEPART(MONTH, [Period]) = DATEPART(MONTH, @DATE)) AS b